### ISSUE TITLE
[Component] Modal should not leave margin for Title when Title slot is absent

### ISSUE THREAD

**Issue by mattwilliams85** [brave/leo#355]
I noticed that when not including the title, there's a space left for the title element. They'll be times where we'll want modals without titles. If this is not the case for design, we should make `title` a required element.

<img width="635" alt="Screenshot 2023-08-22 at 10 30 17 AM" src="https://github.com/brave/leo/assets/6961771/7a368d42-24c4-4130-bb15-c4f3e3ca30e7">

**Comment by AlanBreck** [comment]
@aguscruiz, do you anticipate modals without titles, or should we make `title` required?

**Comment by fallaciousreasoning** [comment]
Just weighing in on this, I had a quick crack at hiding it

![image](https://github.com/brave/leo/assets/7678024/86b15418-bd7b-42e7-867c-7bae396469e0)

The padding we apply is slightly uneven (because we pad the bottom a bit more than the sides/top), which looks a bit off to me.

Because title is set via a slot, we can't enforce that it be present at compile time, so the best we could do is a runtime error (and even then, the user could just pass us an empty `div`).

**Comment by aguscruiz** [comment]
> @aguscruiz, do you anticipate modals without titles, or should we make `title` required?

Yeah I think it's definetely possible a modal won't have titles or bottom actions

**Comment by nullhook** [comment]
![image](https://github.com/brave/leo/assets/8665427/e9e64120-6afe-40de-9ab1-d04b41a8f4c7)

facing this issue currently in Leo, the AI chat
