### ISSUE TITLE
Component: Modal window

### ISSUE THREAD

**Issue by aguscruiz** [brave/leo#71]
https://www.figma.com/file/H11ZOl6JMYbCTW4ZJXqR5V/%F0%9F%96%A5-Desktop-%26-Web?node-id=138%3A10797

![image](https://user-images.githubusercontent.com/15734630/199500492-4a38f4a5-3789-43b6-85e5-a0908b54b24f.png)

**Comment by OAuthBringer** [comment]
Required for Creators 2.0

**Comment by fallaciousreasoning** [comment]
@aguscruiz I can't seem to find this component in Figma

**Comment by aguscruiz** [comment]
Sorry! Must've moved it. Here it is:
https://www.figma.com/file/445ratdeFt26kKk53LSMj0/%F0%9F%92%BB-Websites?node-id=1-6363

**Comment by fallaciousreasoning** [comment]
I'm working on this at the moment. Here are some notes from out last meeting:

## Dialog vs Modal
Dialogs and Modals are very similar, but modals have a backdrop while dialogs don't. We'll handle this with a `modal` property which can be added to a dialog.

In addition, it **might** be possible to scroll the content behind a dialog (but not a modal). Dialogs also (currently) only support the `small` size, while dialogs also have a bigger mode.

`back`/`close` button should be supported via boolean flags. The back button should fire a `back` event, and is intended for use in multi step wizards.

## Slots

The component should have the following slots:
- Title
- Subtitle (doesn't affect layout when not present)
- Body
- Actions

## Imperative API

It should be possible to use the component via an imperative API, allowing us to use the dialog component instead of the `window.alert`, `window.confirm` and `window.prompt` functions.
